sudo: false

language: python

dist: focal

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

env:
  - PARSER=native

addons:
  apt:
    packages:
    - mediainfo
    - ffmpeg

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - pip install --upgrade pytest

install:
  - pip install tox-travis
  - pip install -e .

script: tox

after_script:
  - tox -e lint
  - tox -e type-check
