sudo: false

language: python

dist: xenial

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  - PARSER=native

addons:
  apt:
    packages:
    - mediainfo
    - ffmpeg

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - pip install --upgrade pytest

install:
  - pip install -e .

script: python setup.py test --addopts "--verbose $PYTEST_ADDOPTS"
